In [1]:
from glob import glob
import pandas as pd
import numpy as np
import os
import json
from collections import defaultdict

In [3]:
# df_movies = pd.read_csv('dataset/tmdb_5000_movies.csv')
# df_movies = df_movies.dropna(subset=['overview', 'release_date', 'runtime'])
# df_movies.isnull().sum()
# df_movies.to_csv("dataset/tmdb_5000_movies_nonull.csv")

In [4]:
df = pd.read_csv('dataset/tmdb_5000_movies_nonull.csv')
# df_movies.loc[:,['id', 'keywords', 'genres', 'title']]
# df_credits = pd.read_csv('dataset/tmdb_5000_credits.csv')

df = df[['budget', 'genres', 'keywords', 'original_language'
                      , 'overview', 'popularity', 'production_companies'
                     , 'production_countries', 'release_date', 'revenue'
                     , 'runtime', 'spoken_languages', 'tagline', 'title'
                     , 'vote_average', 'vote_count']]
display(df.sort_values(by='release_date', ascending=False).head())
# display(df_credits.head())

,budget,genres,keywords,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,tagline,title,vote_average,vote_count
4253,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10751, ""...",[],en,"In 1979, an Indian family moves to America wit...",0.710870,[],[],2017-02-03,0,102.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",It’s better to stand out than to fit in.,Growing Up Smith,7.4,7
3407,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...","[{""id"": 1415, ""name"": ""small town""}, {""id"": 46...",en,Set in a small town near the North Pole where ...,3.139294,[],[],2016-10-02,0,96.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",NaN,Two Lovers and a Bear,6.8,27
3301,8000000,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 1650, ""name"": ""cook""}, {""id"": 6054, ""n...",en,A unique friendship develops when a little gir...,7.828459,"[{""name"": ""Envision Media Arts"", ""id"": 19456},...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-09-16,0,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",He was the one person she could always count on.,Mr. Church,7.0,129
3248,0,"[{""id"": 12, ""name"": ""Adventure""}]","[{""id"": 3405, ""name"": ""blow job""}, {""id"": 1173...",en,When his hard-earned kicks get snatched by a l...,3.467923,"[{""name"": ""Bystorm Films"", ""id"": 2903}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-09-09,0,80.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",They aren't just shoes,Kicks,7.5,18
4716,8500000,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 2831, ""name"": ""slavery""}]",en,"Nat Turner, a former slave in America, leads a...",9.452808,"[{""name"": ""Phantom Four"", ""id"": 423}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-09-09,15861566,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Untold Story of Nat Turner,The Birth of a Nation,6.5,178

In [5]:
def convert_list(cell):
    """convert the json format to a list of categories"""
    kw_list = []
    for kw in json.loads(cell):
        kw_list.append(kw['name'])
    return kw_list


def larger_n(col, n):
    """filter the column"""
    keywords = defaultdict(int)
    for row in df_movies[col]:
        row = json.loads(row)
        for entry in row:
            keywords[entry['name']] += 1
    kw_cnt = sorted(keywords.items(), key=lambda x: -x[1])
    return [kw[0] for kw in kw_cnt if kw[1] >= n]

df_movies = df

larger_kw = larger_n('keywords', 30)
larger_genre = larger_n('genres', 0)
larger_pc = larger_n('production_companies', 5)
larger_pcount = larger_n('production_countries', 3)
larger_lang = larger_n('spoken_languages', 10)

df_movies['keywords'] = df_movies['keywords'].apply(
    convert_list).apply(lambda cell: [kw for kw in cell if kw in larger_kw])
# df_movies['keywords'] = df_movies['keywords'].apply(convert_list)
df_movies['genres'] = df_movies['genres'].apply(convert_list).apply(
    lambda cell: [kw for kw in cell if kw in larger_genre])
df_movies['production_companies'] = df_movies['production_companies'].apply(convert_list).apply(
    lambda cell: [kw for kw in cell if kw in larger_pc])
df_movies['production_countries'] = df_movies['production_countries'].apply(convert_list).apply(
    lambda cell: [kw for kw in cell if kw in larger_pcount])
df_movies['spoken_languages'] = df_movies['spoken_languages'].apply(convert_list).apply(
    lambda cell: [kw for kw in cell if kw in larger_lang])

df_movies

,budget,genres,keywords,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,tagline,title,vote_average,vote_count
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]","[future, alien, soldier, battle, 3d]",en,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[Ingenious Film Partners, Twentieth Century Fo...","[United States of America, United Kingdom]",2009-12-10,2787965087,162.0,"[English, Español]",Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[Adventure, Fantasy, Action]","[love of one's life, ship, aftercreditsstinger]",en,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[Walt Disney Pictures, Jerry Bruckheimer Films]",[United States of America],2007-05-19,961000000,169.0,[English],"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[Action, Adventure, Crime]","[spy, based on novel, sequel]",en,A cryptic message from Bond’s past sends him o...,107.376788,"[Columbia Pictures, Danjaq]","[United Kingdom, United States of America]",2015-10-26,880674609,148.0,"[Français, English, Español, Italiano, Deutsch]",A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[Action, Crime, Drama, Thriller]","[terrorist, secret identity, superhero]",en,Following the death of District Attorney Harve...,112.312950,"[Legendary Pictures, Warner Bros., DC Entertai...",[United States of America],2012-07-16,1084939099,165.0,[English],The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[Action, Adventure, Science Fiction]","[based on novel, alien, escape, 3d]",en,"John Carter is a war-weary, former military ca...",43.926995,[Walt Disney Pictures],[United States of America],2012-03-07,284139100,132.0,[English],"Lost in our world, found in another.",John Carter,6.1,2124
5,258000000,"[Fantasy, Action, Adventure]","[love of one's life, marvel comic, sequel, sup...",en,The seemingly invincible Spider-Man goes up ag...,115.699814,"[Columbia Pictures, Laura Ziskin Productions, ...",[United States of America],2007-05-01,890871626,139.0,"[English, Français]",The battle within.,Spider-Man 3,5.9,3576
6,260000000,"[Animation, Family]","[hostage, magic, musical, duringcreditsstinger]",en,When the kingdom's most wanted-and most charmi...,48.681969,"[Walt Disney Pictures, Walt Disney Animation S...",[United States of America],2010-11-24,591794936,100.0,[English],They're taking adventure to new lengths.,Tangled,7.4,3330
7,280000000,"[Action, Adventure, Science Fiction]","[marvel comic, sequel, superhero, based on com...",en,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[Marvel Studios, Revolution Sun Studios]",[United States of America],2015-04-22,1405403694,141.0,[English],A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
8,250000000,"[Adventure, Fantasy, Family]","[witch, magic]",en,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[Warner Bros., Heyday Films]","[United Kingdom, United States of America]",2009-07-07,933959197,153.0,[English],Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
9,250000000,"[Action, Adventure, Fantasy]","[superhero, based on comic book, revenge]",en,Fearing the actions of a god-like Super Hero l...,155.790452,"[DC Comics, Atlas Entertainment, Warner Bros.,...",[United States of America],2016-03-23,873260194,151.0,[English],Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004
10,270000000,"[Adventure, Fantasy, Action, Science Fiction]","[saving the world, sequel, superhero, based on...",en,Superman returns to discover his 5-year absenc...,57.925623,"[DC Comics, Legendary Pictures, Warner Bros., ...",[United States of America],2006-06-28,391081192,154.0,"[English, Français, Deutsch]",NaN,Superman Returns,5.4,1400
11,200000000,"[Adventure, Action, Thriller, Crime]",[undercover],en,Quantum of Solace continues the adventures of ...,107.928811,[Eon Productions],"[United Kingdom, United States of America]",2008-10-30,586090727,106.0,"[English, Español, Italiano, Français, Deutsch]","For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965
12,200000000,"[Adventure, Fantasy, Action]","[witch, monster, ship, daughter, aftercreditss...",en,Captain Jack Sparrow works his way out of a bl...,145.847379,"[Walt Disney Pictures, Jerry Bruckheimer Films]","[United States of America, Bahamas]",2006-06-20,1065659812,151.0,"[English, Türkçe, ελληνικά, 普通话]",Jack is back!,Pirates of the Caribbean: Dead Man's Chest,7.0,5246
13,255000000,"[Action, Adventure, Western]","[escape, lawyer]",en,The Texas Rangers chase down a gang of outlaws...,49.046956,"[Walt Disney Pictures, Jerry Bruckheimer Films]",[United States of America],2013-07-03,89289910,149.0,[English],Never Take Off the Mask,The Lone Ranger,5.9,2311
14,225000000,"[Action, Adventure, Fantasy, Science Fiction]","[saving the world, superhero, based on comic b...",en,A young boy learns that he has extraordinary p...,99.398009,"[Legendary Pictures, Warner Bros., DC Entertai...","[United Kingdom, United States of America]",2013-06-12,662845518,143.0,[English],You will believe that a man can fly.,Man of Steel,6.5,6359
15,225000000,"[Adventure, Family, Fantasy]","[based on novel, brother sister relationship]",en,One year after their incredible adventures in ...,53.978602,"[Walt Disney, Walden Media, Stillking Films, R...","[Czech Republic, Poland, United States of Amer...",2008-05-15,419651413,150.0,[English],Hope has a new face.,The Chronicles of Narnia: Prince Caspian,6.3,1630
16,220000000,"[Science Fiction, Action, Adventure]","[new york, marvel comic, superhero, based on c...",en,When an unexpected enemy emerges and threatens...,144.448633,"[Paramount Pictures, Marvel Studios]",[United States of America],2012-04-25,1519557910,143.0,[English],Some assembly required.,The Avengers,7.4,11776
17,380000000,"[Adventure, Action, Fantasy]","[ship, soldier, battle, aftercreditsstinger, 3d]",en,Captain Jack Sparrow crosses paths with a woma...,135.413856,"[Walt Disney Pictures, Jerry Bruckheimer Films...",[United States of America],2011-05-14,1045713802,136.0,"[English, Español]",Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948
18,225000000,"[Action, Comedy, Science Fiction]","[time travel, alien]",en,Agents J (Will Smith) and K (Tommy Lee Jones) ...,52.035179,"[Amblin Entertainment, Imagenation Abu Dhabi F...",[United States of America],2012-05-23,624026776,106.0,[English],They are back... in time.,Men in Black 3,6.2,4160
19,250000000,"[Action, Adventure, Fantasy]","[corruption, battle]",en,Immediately after the events of The Desolation...,120.965743,"[WingNut Films, New Line Cinema, Warner Bros. ...","[New Zealand, United States of America]",2014-12-10,956019788,144.0,[English],Witness the defining chapter of the Middle-Ear...,The Hobbit: The Battle of the Five Armies,7.1,4760
20,215000000,"[Action, Adventure, Fantasy]","[marvel comic, duringcreditsstinger]",en,Peter Parker is an outcast high schooler aband...,89.866276,"[Columbia Pictures, Laura Ziskin Productions, ...",[United States of America],2012-06-27,752215857,136.0,[English],The untold story begins.,The Amazing Spider-Man,6.5,6586
21,200000000,"[Action, Adventure]",[],en,When soldier Robin happens upon the dying Robe...,37.668301,"[Imagine Entertainment, Universal Pictures, Sc...","[United Kingdom, United States of America]",2010-05-12,310669540,140.0,"[English, ภาษาไทย]","Rise and rise again, until lambs become lions.",Robin Hood,6.2,1398
22,250000000,"[Adventure, Fantasy]",[],en,"The Dwarves, Bilbo and Gandalf have successful...",94.370564,"[WingNut Films, New Line Cinema, Warner Bros. ...","[New Zealand, United States of America]",2013-12-11,958400000,161.0,[English],Beyond darkness... beyond desolation... lies t...,The Hobbit: The Desolation of Smaug,7.6,4524
23,180000000,"[Adventure, Fantasy]","[england, based on young adult novel]",en,"After overhearing a shocking secret, precociou...",42.990906,"[New Line Cinema, Ingenious Film Partners, Dep...","[United Kingdom, United States of America]",2007-12-04,372234864,113.0,"[English, Pусский, Français]",There are worlds beyond our own - the compass ...,The Golden Compass,5.8,1303
24,207000000,"[Adventure, Drama, Action]","[monster, ship]",en,"In 1933 New York, an overly ambitious movie pr...",61.226010,"[WingNut Films, Universal Pictures]","[New Zealand, United States of America, Germany]",2005-12-14,550000000,187.0,[English],The eighth wonder of the world.,King Kong,6.6,2337
25,200000000,"[Drama, Romance, Thriller]","[ship, love, 3d]",en,"84 years later, a 101-year-old woman named Ros...",100.025899,"[Paramount Pictures, Twentieth Century Fox Fil...",[United States of America],1997-11-18,1845034188,194.0,"[English, Français, Deutsch, svenska, Italiano...",Nothing on Earth could come between them.,Titanic,7.5,7562
26,250000000,"[Adventure, Action, Science Fiction]","[war, marvel comic, sequel, superhero, based o...",en,"Following the events of Age of Ultron, the col...",198.372395,"[Studio Babelsberg, Marvel Studios, Walt Disne...",[United States of America],2016-04-27,1153304495,147.0,"[Română, English, Deutsch, Pусский]",Divided We Fall,Captain America: Civil War,7.1,7241
27,209000000,"[Thriller, Action, Adventure, Science Fiction]","[fight, scientist, aftercreditsstinger]",en,"When mankind beams a radio signal into space, ...",64.928382,"[Universal Pictures, Bluegrass Films]",[United States of America],2012-04-11,303025485,131.0,"[English, ภาษาไทย]",The Battle for Earth Begins at Sea,Battleship,5.5,2114
28,150000000,"[Action, Adventure, Science Fiction, Thriller]","[monster, island, sequel, suspense, escape, 3d]",en,Twenty-two years after the events of Jurassic ...,418.708552,"[Universal Studios, Amblin Entertainment, Lege...",[United States of America],2015-06-09,1513528810,124.0,[English],The park is open.,Jurassic World,6.5,8662
29,200000000,"[Action, Adventure, Thriller]",[spy],en,When Bond's latest assignment goes gravely wro...,93.004993,[Columbia Pictures],"[United Kingdom, United States of America]",2012-10-25,1108561013,143.0,[English],Think on your sins.,Skyfall,6.9,7604
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4769,27000,[Comedy],[aftercreditsstinger],en,Convenience and video store clerks Dante and R...,19.748658,"[Miramax Films, View Askew Productions]",[United States of America],1994-09-13,3151130,92.0,[English],Just because they serve you doesn't mean they ...,Clerks,7.4,755
4770,27000,"[Drama, Romance]",[dream],en,An erotic poem set in the fantasies of a young...,0.027811,[],[United States of America],1971-01-01,0,64.0,"[English, Français]",A unique experience in visual fantasy!,Pink Narcissus,6.0,9
4771,0,"[Drama, Comedy]",[],en,"Unsure of what to do next, 23-year-old Marnie ...",0.362633,[],[United States of America],2002-09-20,76901,85.0,[English],NaN,Funny Ha Ha,6.3,8
4772,0,"[Comedy, Drama]","[love, independent film]",en,Two business executives--one an avowed misogyn...,2.634007,[Alliance Atlantis Communications],"[Canada, United States of America]",1997-01-19,0,97.0,[English],Are all men bastards...or just misunderstood?,In the Company of Men,6.8,44
4773,0,[Drama],[],en,"Fifteen years ago, their Washington Heights ne...",0.039264,[],[United States of America],2002-01-15,0,78.0,"[Español, English]",NaN,Manito,5.5,2
4774,0,"[Action, Drama, Crime, Thriller]",[],en,The boredom of small town life is eating Bill ...,7.101197,[Brightlight Pictures],"[Canada, Germany]",2009-08-14,0,85.0,[English],Vengeance is ruthless.,Rampage,6.0,131
4775,0,[Comedy],"[dream, independent film]",en,"Presents a day in the life in Austin, Texas am...",3.320622,[],[United States of America],1990-07-27,0,97.0,[English],NaN,Slacker,6.4,77
4776,0,"[Thriller, Crime, Drama]",[],en,A desperate ex-con is forced to gather his old...,0.038143,[],[],2015-10-02,0,90.0,[],NaN,Dutch Kills,0.0,0
4777,22000,"[Comedy, Romance]",[divorce],en,Sasha tries to get her soon-to-be ex husband K...,0.048948,[],[United States of America],2013-02-14,0,90.0,[English],Getting divorced does funny things to a girl,Dry Spell,6.0,1
4778,0,"[Drama, Family]",[father son relationship],en,"Jay Austin wants to sell you a used car, but w...",1.048524,[],[United States of America],2003-01-01,0,120.0,[English],NaN,Flywheel,6.8,19
4779,0,"[Thriller, Horror]",[],en,"During an all-night, drug-fueled party at an a...",3.619167,[],[United States of America],2015-01-16,0,91.0,[English],nederlands,Backmask,4.7,79
4780,0,"[Drama, Comedy, Romance]",[],en,Josh's life is pretty much in the toilet. He's...,1.243955,[],[],2005-01-17,0,85.0,[],NaN,The Puffy Chair,6.2,15
4781,0,[Drama],[],en,Created by the members of a Nairobi-based arts...,0.327794,[],[],2014-09-05,0,60.0,[English],NaN,Stories of Our Lives,0.0,0
4782,0,"[Comedy, Romance]",[independent film],en,"'Breaking Upwards' explores a young, real-life...",0.674570,[],[United States of America],2009-03-14,0,88.0,[English],NaN,Breaking Upwards,5.6,12
4783,0,"[Science Fiction, Thriller]",[superhero],en,"Masked vigilantes Charge (Jason Trost), Cutthr...",3.545991,[],[],2011-10-26,0,78.0,[English],May The Best Man Win,All Superheroes Must Die,4.2,13
4784,12000,"[Horror, Comedy, Crime]","[gay, drug dealer, independent film]",en,Notorious Baltimore criminal and underground f...,4.553644,[],[United States of America],1972-03-12,6000000,93.0,[English],An exercise in poor taste.,Pink Flamingos,6.2,110
4785,0,[Drama],[],en,"After losing her husband to a heroin overdose,...",1.464566,[],"[United Kingdom, France, Canada]",2004-09-01,0,111.0,"[广州话 / 廣州話, English, Français]","When you don't have a choice, you change.",Clean,6.7,17
4786,0,"[Drama, Foreign]",[],fa,Various women struggle to function in the oppr...,1.193779,[],[Iran],2000-09-08,0,90.0,[فارسی],NaN,The Circle,6.6,17
4787,13,[Horror],[],en,Recently dumped by his girlfirend for another ...,0.332679,[],[Ireland],2007-01-01,0,84.0,[English],Everything You've Heard is True,Tin Can Man,2.0,1
4788,20000,"[Crime, Horror, Mystery, Thriller]","[prostitute, hotel, based on novel, investigat...",ja,A wave of gruesome murders is sweeping Tokyo. ...,0.212443,[],[Japan],1997-11-06,99000,111.0,[日本語],Madness. Terror. Murder.,Cure,7.4,63
4789,0,[Drama],[],en,Isaac and Angel are two young Latinos involved...,0.029757,[],[United States of America],2004-04-11,0,90.0,[],Two gangs. One secret. One crossroad.,On The Downlow,6.0,2
4790,0,"[Thriller, Horror, Comedy]",[],en,"It should have been just a normal day of sex, ...",0.166513,[],[United States of America],2012-01-20,0,82.0,[English],NaN,Sanctuary: Quite a Conundrum,0.0,0
4791,0,[Drama],[gang],en,A young woman in L.A. is having a bad day: she...,0.918116,[],[United States of America],1995-09-09,0,98.0,[English],Sometimes you've got to break the rules,Bang,6.0,1
4792,7000,"[Science Fiction, Drama, Thriller]","[time travel, independent film]",en,Friends/fledgling entrepreneurs invent a devic...,23.307949,[],[United States of America],2004-10-08,424760,77.0,[English],What happens if it actually works?,Primer,6.9,658
4793,0,"[Foreign, Thriller]",[],en,"Adam, a security guard, travels from Californi...",0.022173,[],[],2005-03-12,0,80.0,[],NaN,Cavite,7.5,2
4794,220000,"[Action, Crime, Thriller]",[],es,El Mariachi just wants to play his guitar and ...,14.269792,[Columbia Pictures],"[Mexico, United States of America]",1992-09-04,2040920,81.0,[Español],"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4795,9000,"[Comedy, Romance]",[],en,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4796,0,"[Comedy, Drama, Romance, TV Movie]",[investigation],en,"""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,[],[United States of America],2013-10-13,0,120.0,[English],NaN,"Signed, Sealed, Delivered",7.0,6
4797,0,[],[],en,When ambitious New York attorney Sam is sent t...,0.857008,[],"[United States of America, China]",2012-05-03,0,98.0,[English],A New Yorker in Shanghai,Shanghai Calling,5.7,7
4798,0,[Documentary],[obsession],en,Ever since the second grade when he first saw ...,1.929883,[],[United States of America],2005-08-05,0,90.0,[English],NaN,My Date with Drew,6.3,16

# Feature Engineering

## Overview -- Tfidf

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

df_movies = df_movies.loc[df_movies.overview.apply(lambda x: len(x)>10)]
df_movies = df_movies.reset_index(drop=True)

v = TfidfVectorizer(stop_words='english',binary=True, ngram_range=(1, 2),min_df=0.001)
x = v.fit_transform(df_movies['overview'])

overview = pd.DataFrame(x.toarray(), columns=list(range(x.toarray().shape[1])))

## budget + revenue

In [7]:
df_movies.loc[(df_movies.budget<100)].shape

(1057, 16)

for these, use revenue + overview + popularity + release_date to predict the budget

In [8]:
df_movies.loc[(df_movies.budget<100) & (df_movies.revenue>100)].shape

(145, 16)

In [9]:
def predict_budget1(dataset):
    from sklearn import ensemble
    
    data_p = dataset[['revenue','popularity','budget']]
    v = TfidfVectorizer(stop_words='english',binary=True, ngram_range=(1, 2),min_df=0.001)
    x = v.fit_transform(dataset['overview'])
    overview = pd.DataFrame(x.toarray(), columns=list(range(x.toarray().shape[1])))
    data_p = pd.concat([data_p, overview], axis=1)
    
    x_train = data_p.loc[~(data_p.budget<100) & (data_p.revenue>100)].drop('budget', 1)
    y_train = data_p.loc[~(data_p.budget<100) & (data_p.revenue>100)]['budget']
    x_test = data_p.loc[(data_p.budget<100) & (data_p.revenue>100)].drop('budget', 1)
    
    rfr = ensemble.RandomForestRegressor(random_state=42)
    rfr.fit(x_train,y_train)
    
    y_test = rfr.predict(x_test)
    return y_test

df_movies.loc[(df_movies.budget<100) & (df_movies.revenue>100), 'budget'] = predict_budget1(df_movies)

/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [10]:
df_movies.loc[(df_movies.budget<100) & (df_movies.revenue>100)].shape

(0, 16)

for others, use overview+popularity+release_date to predict budget

In [11]:
df_movies.loc[(df_movies.budget<100)].shape

(912, 16)

In [12]:
def predict_budget2(dataset):
    from sklearn import ensemble
    data_p = dataset[['popularity','budget']]
    v = TfidfVectorizer(stop_words='english',binary=True, ngram_range=(1, 2),min_df=0.001)
    x = v.fit_transform(dataset['overview'])
    overview = pd.DataFrame(x.toarray(), columns=list(range(x.toarray().shape[1])))
    data_p = pd.concat([data_p, overview], axis=1)
    
    x_train = data_p.loc[~(data_p.budget<100)].drop('budget', 1)
    y_train = data_p.loc[~(data_p.budget<100)]['budget']
    x_test = data_p.loc[(data_p.budget<100) & (df_movies.revenue<=100)].drop('budget', 1)
    
    rfr = ensemble.RandomForestRegressor(random_state=42)
    rfr.fit(x_train,y_train)
    print(x_test.shape)
    y_test = rfr.predict(x_test)
    return y_test

df_movies.loc[(df_movies.budget<100) & (df_movies.revenue<=100), 'budget'] = predict_budget2(df_movies)

/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

(912, 5561)

In [13]:
df_movies.loc[(df_movies.budget<100)].shape

(0, 16)

## runtime

## keywords + tagline

## original_language + spoken_language
1) original language is the language of production. 2) spoken language is the language of production too and add the languages in case of multi-language in the movie.

## production_companies

## production_countries

## release_date

## popularity + vote_average + vote_count

In [14]:
df_movies.loc[df_movies['popularity']==0]

Empty DataFrame
Columns: [budget, genres, keywords, original_language, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, spoken_languages, tagline, title, vote_average, vote_count]
Index: []

# Result-dataset

In [15]:
df_movies = df_movies.reset_index(drop=True)

In [16]:
df_movies

,budget,genres,keywords,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,tagline,title,vote_average,vote_count
0,2.370000e+08,"[Action, Adventure, Fantasy, Science Fiction]","[future, alien, soldier, battle, 3d]",en,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[Ingenious Film Partners, Twentieth Century Fo...","[United States of America, United Kingdom]",2009-12-10,2787965087,162.0,"[English, Español]",Enter the World of Pandora.,Avatar,7.2,11800
1,3.000000e+08,"[Adventure, Fantasy, Action]","[love of one's life, ship, aftercreditsstinger]",en,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[Walt Disney Pictures, Jerry Bruckheimer Films]",[United States of America],2007-05-19,961000000,169.0,[English],"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,2.450000e+08,"[Action, Adventure, Crime]","[spy, based on novel, sequel]",en,A cryptic message from Bond’s past sends him o...,107.376788,"[Columbia Pictures, Danjaq]","[United Kingdom, United States of America]",2015-10-26,880674609,148.0,"[Français, English, Español, Italiano, Deutsch]",A Plan No One Escapes,Spectre,6.3,4466
3,2.500000e+08,"[Action, Crime, Drama, Thriller]","[terrorist, secret identity, superhero]",en,Following the death of District Attorney Harve...,112.312950,"[Legendary Pictures, Warner Bros., DC Entertai...",[United States of America],2012-07-16,1084939099,165.0,[English],The Legend Ends,The Dark Knight Rises,7.6,9106
4,2.600000e+08,"[Action, Adventure, Science Fiction]","[based on novel, alien, escape, 3d]",en,"John Carter is a war-weary, former military ca...",43.926995,[Walt Disney Pictures],[United States of America],2012-03-07,284139100,132.0,[English],"Lost in our world, found in another.",John Carter,6.1,2124
5,2.580000e+08,"[Fantasy, Action, Adventure]","[love of one's life, marvel comic, sequel, sup...",en,The seemingly invincible Spider-Man goes up ag...,115.699814,"[Columbia Pictures, Laura Ziskin Productions, ...",[United States of America],2007-05-01,890871626,139.0,"[English, Français]",The battle within.,Spider-Man 3,5.9,3576
6,2.600000e+08,"[Animation, Family]","[hostage, magic, musical, duringcreditsstinger]",en,When the kingdom's most wanted-and most charmi...,48.681969,"[Walt Disney Pictures, Walt Disney Animation S...",[United States of America],2010-11-24,591794936,100.0,[English],They're taking adventure to new lengths.,Tangled,7.4,3330
7,2.800000e+08,"[Action, Adventure, Science Fiction]","[marvel comic, sequel, superhero, based on com...",en,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[Marvel Studios, Revolution Sun Studios]",[United States of America],2015-04-22,1405403694,141.0,[English],A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
8,2.500000e+08,"[Adventure, Fantasy, Family]","[witch, magic]",en,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[Warner Bros., Heyday Films]","[United Kingdom, United States of America]",2009-07-07,933959197,153.0,[English],Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
9,2.500000e+08,"[Action, Adventure, Fantasy]","[superhero, based on comic book, revenge]",en,Fearing the actions of a god-like Super Hero l...,155.790452,"[DC Comics, Atlas Entertainment, Warner Bros.,...",[United States of America],2016-03-23,873260194,151.0,[English],Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004
10,2.700000e+08,"[Adventure, Fantasy, Action, Science Fiction]","[saving the world, sequel, superhero, based on...",en,Superman returns to discover his 5-year absenc...,57.925623,"[DC Comics, Legendary Pictures, Warner Bros., ...",[United States of America],2006-06-28,391081192,154.0,"[English, Français, Deutsch]",NaN,Superman Returns,5.4,1400
11,2.000000e+08,"[Adventure, Action, Thriller, Crime]",[undercover],en,Quantum of Solace continues the adventures of ...,107.928811,[Eon Productions],"[United Kingdom, United States of America]",2008-10-30,586090727,106.0,"[English, Español, Italiano, Français, Deutsch]","For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965
12,2.000000e+08,"[Adventure, Fantasy, Action]","[witch, monster, ship, daughter, aftercreditss...",en,Captain Jack Sparrow works his way out of a bl...,145.847379,"[Walt Disney Pictures, Jerry Bruckheimer Films]","[United States of America, Bahamas]",2006-06-20,1065659812,151.0,"[English, Türkçe, ελληνικά, 普通话]",Jack is back!,Pirates of the Caribbean: Dead Man's Chest,7.0,5246
13,2.550000e+08,"[Action, Adventure, Western]","[escape, lawyer]",en,The Texas Rangers chase down a gang of outlaws...,49.046956,"[Walt Disney Pictures, Jerry Bruckheimer Films]",[United States of America],2013-07-03,89289910,149.0,[English],Never Take Off the Mask,The Lone Ranger,5.9,2311
14,2.250000e+08,"[Action, Adventure, Fantasy, Science Fiction]","[saving the world, superhero, based on comic b...",en,A young boy learns that he has extraordinary p...,99.398009,"[Legendary Pictures, Warner Bros., DC Entertai...","[United Kingdom, United States of America]",2013-06-12,662845518,143.0,[English],You will believe that a man can fly.,Man of Steel,6.5,6359
15,2.250000e+08,"[Adventure, Family, Fantasy]","[based on novel, brother sister relationship]",en,One year after their incredible adventures in ...,53.978602,"[Walt Disney, Walden Media, Stillking Films, R...","[Czech Republic, Poland, United States of Amer...",2008-05-15,419651413,150.0,[English],Hope has a new face.,The Chronicles of Narnia: Prince Caspian,6.3,1630
16,2.200000e+08,"[Science Fiction, Action, Adventure]","[new york, marvel comic, superhero, based on c...",en,When an unexpected enemy emerges and threatens...,144.448633,"[Paramount Pictures, Marvel Studios]",[United States of America],2012-04-25,1519557910,143.0,[English],Some assembly required.,The Avengers,7.4,11776
17,3.800000e+08,"[Adventure, Action, Fantasy]","[ship, soldier, battle, aftercreditsstinger, 3d]",en,Captain Jack Sparrow crosses paths with a woma...,135.413856,"[Walt Disney Pictures, Jerry Bruckheimer Films...",[United States of America],2011-05-14,1045713802,136.0,"[English, Español]",Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948
18,2.250000e+08,"[Action, Comedy, Science Fiction]","[time travel, alien]",en,Agents J (Will Smith) and K (Tommy Lee Jones) ...,52.035179,"[Amblin Entertainment, Imagenation Abu Dhabi F...",[United States of America],2012-05-23,624026776,106.0,[English],They are back... in time.,Men in Black 3,6.2,4160
19,2.500000e+08,"[Action, Adventure, Fantasy]","[corruption, battle]",en,Immediately after the events of The Desolation...,120.965743,"[WingNut Films, New Line Cinema, Warner Bros. ...","[New Zealand, United States of America]",2014-12-10,956019788,144.0,[English],Witness the defining chapter of the Middle-Ear...,The Hobbit: The Battle of the Five Armies,7.1,4760
20,2.150000e+08,"[Action, Adventure, Fantasy]","[marvel comic, duringcreditsstinger]",en,Peter Parker is an outcast high schooler aband...,89.866276,"[Columbia Pictures, Laura Ziskin Productions, ...",[United States of America],2012-06-27,752215857,136.0,[English],The untold story begins.,The Amazing Spider-Man,6.5,6586
21,2.000000e+08,"[Action, Adventure]",[],en,When soldier Robin happens upon the dying Robe...,37.668301,"[Imagine Entertainment, Universal Pictures, Sc...","[United Kingdom, United States of America]",2010-05-12,310669540,140.0,"[English, ภาษาไทย]","Rise and rise again, until lambs become lions.",Robin Hood,6.2,1398
22,2.500000e+08,"[Adventure, Fantasy]",[],en,"The Dwarves, Bilbo and Gandalf have successful...",94.370564,"[WingNut Films, New Line Cinema, Warner Bros. ...","[New Zealand, United States of America]",2013-12-11,958400000,161.0,[English],Beyond darkness... beyond desolation... lies t...,The Hobbit: The Desolation of Smaug,7.6,4524
23,1.800000e+08,"[Adventure, Fantasy]","[england, based on young adult novel]",en,"After overhearing a shocking secret, precociou...",42.990906,"[New Line Cinema, Ingenious Film Partners, Dep...","[United Kingdom, United States of America]",2007-12-04,372234864,113.0,"[English, Pусский, Français]",There are worlds beyond our own - the compass ...,The Golden Compass,5.8,1303
24,2.070000e+08,"[Adventure, Drama, Action]","[monster, ship]",en,"In 1933 New York, an overly ambitious movie pr...",61.226010,"[WingNut Films, Universal Pictures]","[New Zealand, United States of America, Germany]",2005-12-14,550000000,187.0,[English],The eighth wonder of the world.,King Kong,6.6,2337
25,2.000000e+08,"[Drama, Romance, Thriller]","[ship, love, 3d]",en,"84 years later, a 101-year-old woman named Ros...",100.025899,"[Paramount Pictures, Twentieth Century Fox Fil...",[United States of America],1997-11-18,1845034188,194.0,"[English, Français, Deutsch, svenska, Italiano...",Nothing on Earth could come between them.,Titanic,7.5,7562
26,2.500000e+08,"[Adventure, Action, Science Fiction]","[war, marvel comic, sequel, superhero, based o...",en,"Following the events of Age of Ultron, the col...",198.372395,"[Studio Babelsberg, Marvel Studios, Walt Disne...",[United States of America],2016-04-27,1153304495,147.0,"[Română, English, Deutsch, Pусский]",Divided We Fall,Captain America: Civil War,7.1,7241
27,2.090000e+08,"[Thriller, Action, Adventure, Science Fiction]","[fight, scientist, aftercreditsstinger]",en,"When mankind beams a radio signal into space, ...",64.928382,"[Universal Pictures, Bluegrass Films]",[United States of America],2012-04-11,303025485,131.0,"[English, ภาษาไทย]",The Battle for Earth Begins at Sea,Battleship,5.5,2114
28,1.500000e+08,"[Action, Adventure, Science Fiction, Thriller]","[monster, island, sequel, suspense, escape, 3d]",en,Twenty-two years after the events of Jurassic ...,418.708552,"[Universal Studios, Amblin Entertainment, Lege...",[United States of America],2015-06-09,1513528810,124.0,[English],The park is open.,Jurassic World,6.5,8662
29,2.000000e+08,"[Action, Adventure, Thriller]",[spy],en,When Bond's latest assignment goes gravely wro...,93.004993,[Columbia Pictures],"[United Kingdom, United States of America]",2012-10-25,1108561013,143.0,[English],Think on your sins.,Skyfall,6.9,7604
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4768,2.700000e+04,[Comedy],[aftercreditsstinger],en,Convenience and video store clerks Dante and R...,19.748658,"[Miramax Films, View Askew Productions]",[United States of America],1994-09-13,3151130,92.0,[English],Just because they serve you doesn't mean they ...,Clerks,7.4,755
4769,2.700000e+04,"[Drama, Romance]",[dream],en,An erotic poem set in the fantasies of a young...,0.027811,[],[United States of America],1971-01-01,0,64.0,"[English, Français]",A unique experience in visual fantasy!,Pink Narcissus,6.0,9
4770,4.007525e+06,"[Drama, Comedy]",[],en,"Unsure of what to do next, 23-year-old Marnie ...",0.362633,[],[United States of America],2002-09-20,76901,85.0,[English],NaN,Funny Ha Ha,6.3,8
4771,1.248000e+07,"[Comedy, Drama]","[love, independent film]",en,Two business executives--one an avowed misogyn...,2.634007,[Alliance Atlantis Communications],"[Canada, United States of America]",1997-01-19,0,97.0,[English],Are all men bastards...or just misunderstood?,In the Company of Men,6.8,44
4772,2.542220e+06,[Drama],[],en,"Fifteen years ago, their Washington Heights ne...",0.039264,[],[United States of America],2002-01-15,0,78.0,"[Español, English]",NaN,Manito,5.5,2
4773,1.200080e+07,"[Action, Drama, Crime, Thriller]",[],en,The boredom of small town life is eating Bill ...,7.101197,[Brightlight Pictures],"[Canada, Germany]",2009-08-14,0,85.0,[English],Vengeance is ruthless.,Rampage,6.0,131
4774,8.270000e+06,[Comedy],"[dream, independent film]",en,"Presents a day in the life in Austin, Texas am...",3.320622,[],[United States of America],1990-07-27,0,97.0,[English],NaN,Slacker,6.4,77
4775,2.620562e+06,"[Thriller, Crime, Drama]",[],en,A desperate ex-con is forced to gather his old...,0.038143,[],[],2015-10-02,0,90.0,[],NaN,Dutch Kills,0.0,0
4776,2.200000e+04,"[Comedy, Romance]",[divorce],en,Sasha tries to get her soon-to-be ex husband K...,0.048948,[],[United States of America],2013-02-14,0,90.0,[English],Getting divorced does funny things to a girl,Dry Spell,6.0,1
4777,2.130738e+06,"[Drama, Family]",[father son relationship],en,"Jay Austin wants to sell you a used car, but w...",1.048524,[],[United States of America],2003-01-01,0,120.0,[English],NaN,Flywheel,6.8,19
4778,1.571550e+07,"[Thriller, Horror]",[],en,"During an all-night, drug-fueled party at an a...",3.619167,[],[United States of America],2015-01-16,0,91.0,[English],nederlands,Backmask,4.7,79
4779,2.095010e+06,"[Drama, Comedy, Romance]",[],en,Josh's life is pretty much in the toilet. He's...,1.243955,[],[],2005-01-17,0,85.0,[],NaN,The Puffy Chair,6.2,15
4780,3.112526e+06,[Drama],[],en,Created by the members of a Nairobi-based arts...,0.327794,[],[],2014-09-05,0,60.0,[English],NaN,Stories of Our Lives,0.0,0
4781,2.060010e+06,"[Comedy, Romance]",[independent film],en,"'Breaking Upwards' explores a young, real-life...",0.674570,[],[United States of America],2009-03-14,0,88.0,[English],NaN,Breaking Upwards,5.6,12
4782,2.024549e+07,"[Science Fiction, Thriller]",[superhero],en,"Masked vigilantes Charge (Jason Trost), Cutthr...",3.545991,[],[],2011-10-26,0,78.0,[English],May The Best Man Win,All Superheroes Must Die,4.2,13
4783,1.200000e+04,"[Horror, Comedy, Crime]","[gay, drug dealer, independent film]",en,Notorious Baltimore criminal and underground f...,4.553644,[],[United States of America],1972-03-12,6000000,93.0,[English],An exercise in poor taste.,Pink Flamingos,6.2,110
4784,3.100022e+06,[Drama],[],en,"After losing her husband to a heroin overdose,...",1.464566,[],"[United Kingdom, France, Canada]",2004-09-01,0,111.0,"[广州话 / 廣州話, English, Français]","When you don't have a choice, you change.",Clean,6.7,17
4785,3.333729e+06,"[Drama, Foreign]",[],fa,Various women struggle to function in the oppr...,1.193779,[],[Iran],2000-09-08,0,90.0,[فارسی],NaN,The Circle,6.6,17
4786,1.319827e+07,[Horror],[],en,Recently dumped by his girlfirend for another ...,0.332679,[],[Ireland],2007-01-01,0,84.0,[English],Everything You've Heard is True,Tin Can Man,2.0,1
4787,2.000000e+04,"[Crime, Horror, Mystery, Thriller]","[prostitute, hotel, based on novel, investigat...",ja,A wave of gruesome murders is sweeping Tokyo. ...,0.212443,[],[Japan],1997-11-06,99000,111.0,[日本語],Madness. Terror. Murder.,Cure,7.4,63
4788,2.085605e+06,[Drama],[],en,Isaac and Angel are two young Latinos involved...,0.029757,[],[United States of America],2004-04-11,0,90.0,[],Two gangs. One secret. One crossroad.,On The Downlow,6.0,2
4789,1.329507e+06,"[Thriller, Horror, Comedy]",[],en,"It should have been just a normal day of sex, ...",0.166513,[],[United States of America],2012-01-20,0,82.0,[English],NaN,Sanctuary: Quite a Conundrum,0.0,0
4790,8.918410e+05,[Drama],[gang],en,A young woman in L.A. is having a bad day: she...,0.918116,[],[United States of America],1995-09-09,0,98.0,[English],Sometimes you've got to break the rules,Bang,6.0,1
4791,7.000000e+03,"[Science Fiction, Drama, Thriller]","[time travel, independent film]",en,Friends/fledgling entrepreneurs invent a devic...,23.307949,[],[United States of America],2004-10-08,424760,77.0,[English],What happens if it actually works?,Primer,6.9,658
4792,1.020000e+06,"[Foreign, Thriller]",[],en,"Adam, a security guard, travels from Californi...",0.022173,[],[],2005-03-12,0,80.0,[],NaN,Cavite,7.5,2
4793,2.200000e+05,"[Action, Crime, Thriller]",[],es,El Mariachi just wants to play his guitar and ...,14.269792,[Columbia Pictures],"[Mexico, United States of America]",1992-09-04,2040920,81.0,[Español],"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4794,9.000000e+03,"[Comedy, Romance]",[],en,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4795,1.617538e+06,"[Comedy, Drama, Romance, TV Movie]",[investigation],en,"""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,[],[United States of America],2013-10-13,0,120.0,[English],NaN,"Signed, Sealed, Delivered",7.0,6
4796,8.160525e+05,[],[],en,When ambitious New York attorney Sam is sent t...,0.857008,[],"[United States of America, China]",2012-05-03,0,98.0,[English],A New Yorker in Shanghai,Shanghai Calling,5.7,7
4797,9.077250e+06,[Documentary],[obsession],en,Ever since the second grade when he first saw ...,1.929883,[],[United States of America],2005-08-05,0,90.0,[English],NaN,My Date with Drew,6.3,16

In [17]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()

genres_dummies = pd.DataFrame(mlb.fit_transform(
    df_movies['genres']), columns=mlb.classes_).add_prefix('genre_')
keywords_dummies = pd.DataFrame(mlb.fit_transform(
    df_movies['keywords']), columns=mlb.classes_).add_prefix('kw_')
df_new = pd.concat([
    df_movies.loc[:, ['budget']],
    genres_dummies, keywords_dummies,
    overview], axis=1)
index_genre = df_new.columns.to_series().apply(lambda x: str(x).startswith('genre_'))
df_y = df_new.loc[:, index_genre]
df_X = df_new.drop(
    df_new.columns[index_genre], inplace=False, axis=1)

In [18]:
df_X

,budget,kw_1970s,kw_3d,kw_adultery,kw_aftercreditsstinger,kw_airplane,kw_alcohol,kw_alien,kw_army,kw_assassin,...,5550,5551,5552,5553,5554,5555,5556,5557,5558,5559
0,2.370000e+08,0,1,0,0,0,0,1,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
1,3.000000e+08,0,0,0,1,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,2.450000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3,2.500000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,2.600000e+08,0,1,0,0,0,0,1,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
5,2.580000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
6,2.600000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
7,2.800000e+08,0,1,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
8,2.500000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
9,2.500000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
10,2.700000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
11,2.000000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
12,2.000000e+08,0,0,0,1,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
13,2.550000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
14,2.250000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
15,2.250000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
16,2.200000e+08,0,0,0,1,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
17,3.800000e+08,0,1,0,1,0,0,0,0,0,...,0.0,0.189759,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
18,2.250000e+08,0,0,0,0,0,0,1,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
19,2.500000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
20,2.150000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
21,2.000000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
22,2.500000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
23,1.800000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
24,2.070000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
25,2.000000e+08,0,1,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
26,2.500000e+08,0,1,0,1,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
27,2.090000e+08,0,0,0,1,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
28,1.500000e+08,0,1,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
29,2.000000e+08,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4768,2.700000e+04,0,0,0,1,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4769,2.700000e+04,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4770,4.007525e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4771,1.248000e+07,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4772,2.542220e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4773,1.200080e+07,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4774,8.270000e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4775,2.620562e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4776,2.200000e+04,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4777,2.130738e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4778,1.571550e+07,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4779,2.095010e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4780,3.112526e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4781,2.060010e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.198461,0.0,0.0,0.0,0.0
4782,2.024549e+07,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4783,1.200000e+04,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4784,3.100022e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4785,3.333729e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4786,1.319827e+07,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4787,2.000000e+04,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4788,2.085605e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4789,1.329507e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4790,8.918410e+05,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4791,7.000000e+03,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4792,1.020000e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4793,2.200000e+05,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4794,9.000000e+03,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4795,1.617538e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4796,8.160525e+05,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4797,9.077250e+06,0,0,0,0,0,0,0,0,0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [19]:
df_y

,genre_Action,genre_Adventure,genre_Animation,genre_Comedy,genre_Crime,genre_Documentary,genre_Drama,genre_Family,genre_Fantasy,genre_Foreign,genre_History,genre_Horror,genre_Music,genre_Mystery,genre_Romance,genre_Science Fiction,genre_TV Movie,genre_Thriller,genre_War,genre_Western
0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
4,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
5,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
6,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
7,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
8,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0
9,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
10,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
11,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
12,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
13,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
14,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
15,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0
16,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
17,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
18,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
19,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
20,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
21,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
23,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
24,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0
26,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
27,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
28,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
29,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4768,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4769,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0
4770,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4771,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4772,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4773,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
4774,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4775,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
4776,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4777,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0
4778,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0
4779,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0
4780,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4781,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4782,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
4783,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
4784,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4785,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4786,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
4787,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0
4788,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4789,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0
4790,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4791,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0
4792,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
4793,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
4794,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4795,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0
4796,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4797,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## get dummies

In [20]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
genres_dummies = pd.DataFrame(mlb.fit_transform(
    df_movies['genres']), columns=mlb.classes_).add_prefix('genre_')
keywords_dummies = pd.DataFrame(mlb.fit_transform(
    df_movies['keywords']), columns=mlb.classes_).add_prefix('kw_')
df_new = pd.concat([
    #df_movies.loc[:, ['budget']],
    genres_dummies, keywords_dummies,
    train_features], axis=1)

df_y = df_new.loc[:, df_new.columns.str.startswith('genre_')]
df_X = df_new.drop(
    df_new.columns[df_new.columns.str.startswith('genre_')], inplace=False, axis=1)

NameError: name 'train_features' is not defined

In [ ]:
df_X

In [21]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(df_X, df_y, test_size=0.33, random_state=42)

In [58]:
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.ensemble import RandomForestClassifier

classifier = BinaryRelevance(RandomForestClassifier())
%time classifier.fit(train_X, train_y)
predictions = classifier.predict(test_X)

from sklearn.metrics import accuracy_score
accuracy_score(test_y, predictions)

/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

CPU times: user 53.4 s, sys: 1.94 s, total: 55.3 s
Wall time: 55.4 s

0.09027777777777778

In [27]:
predictions_dense = predictions.todense()

for i in range(predictions.shape[1]):
    print(accuracy_score(np.asarray(test_y)[:, i], np.asarray(predictions_dense)[:, i]))

0.803030303030303
0.8453282828282829
0.9602272727272727
0.7077020202020202
0.8535353535353535
0.9779040404040404
0.6616161616161617
0.9008838383838383
0.9147727272727273
0.9955808080808081
0.9665404040404041
0.913510101010101
0.9532828282828283
0.9185606060606061
0.8282828282828283
0.9210858585858586
0.9974747474747475
0.7481060606060606
0.9671717171717171
0.9835858585858586

In [57]:
# RF can handle multilabel directly


rf = RandomForestClassifier()
%time rf.fit(train_X, train_y)
predictions = rf.predict(test_X)

from sklearn.metrics import accuracy_score
print(f"Total accuracy: {accuracy_score(test_y, predictions)}")

#predictions_dense = predictions#.todense()

for i in range(predictions.shape[1]):
    print(accuracy_score(test_y.values[:, i], predictions[:, i]))

/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

CPU times: user 1.95 s, sys: 80 ms, total: 2.03 s
Wall time: 2.04 s
Total accuracy: 0.09154040404040405
0.7916666666666666
0.8446969696969697
0.9595959595959596
0.67739898989899
0.8503787878787878
0.9804292929292929
0.6647727272727273
0.8996212121212122
0.9103535353535354
0.9955808080808081
0.9659090909090909
0.9002525252525253
0.9501262626262627
0.9210858585858586
0.8232323232323232
0.9046717171717171
0.9974747474747475
0.7582070707070707
0.9665404040404041
0.9835858585858586

In [56]:
# One vs Rest


from sklearn.multiclass import OneVsRestClassifier
rf = OneVsRestClassifier(RandomForestClassifier())
%time rf.fit(train_X, train_y)
predictions = rf.predict(test_X)

from sklearn.metrics import accuracy_score
print(accuracy_score(test_y, predictions))

for i in range(predictions.shape[1]):
    print(accuracy_score(test_y.values[:, i], predictions[:, i]))

/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/julia/MSDS/Fall18/msds621/miniconda/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

CPU times: user 14.7 s, sys: 1.58 s, total: 16.3 s
Wall time: 16.3 s
0.09343434343434344
0.8093434343434344
0.8459595959595959
0.9583333333333334
0.7108585858585859
0.8503787878787878
0.9772727272727273
0.6609848484848485
0.8996212121212122
0.9147727272727273
0.9955808080808081
0.9659090909090909
0.9097222222222222
0.9507575757575758
0.9185606060606061
0.8238636363636364
0.9292929292929293
0.9974747474747475
0.7657828282828283
0.9671717171717171
0.9835858585858586