In [1]:
from glob import glob
import pandas as pd
import numpy as np
import os
import json
from collections import defaultdict

In [2]:
df_movies = pd.read_csv('dataset/tmdb_5000_movies.csv')
df_credits = pd.read_csv('dataset/tmdb_5000_credits.csv')

In [8]:
display(df_movies.sort_values(by='release_date', ascending=False).head())
display(df_credits.head())

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
4255,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10751, ""...",http://www.growingupsmithmovie.com,426469,[],en,Growing Up Smith,"In 1979, an Indian family moves to America wit...",0.710870,[],[],2017-02-03,0,102.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Itâ€™s better to stand out than to fit in.,Growing Up Smith,7.4,7
3408,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",NaN,325373,"[{""id"": 1415, ""name"": ""small town""}, {""id"": 46...",en,Two Lovers and a Bear,Set in a small town near the North Pole where ...,3.139294,[],[],2016-10-02,0,96.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Two Lovers and a Bear,6.8,27
3302,8000000,"[{""id"": 18, ""name"": ""Drama""}]",NaN,374461,"[{""id"": 1650, ""name"": ""cook""}, {""id"": 6054, ""n...",en,Mr. Church,A unique friendship develops when a little gir...,7.828459,"[{""name"": ""Envision Media Arts"", ""id"": 19456},...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-09-16,0,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,He was the one person she could always count on.,Mr. Church,7.0,129
4720,8500000,"[{""id"": 18, ""name"": ""Drama""}]",http://www.foxsearchlight.com/thebirthofanation/,339408,"[{""id"": 2831, ""name"": ""slavery""}]",en,The Birth of a Nation,"Nat Turner, a former slave in America, leads a...",9.452808,"[{""name"": ""Phantom Four"", ""id"": 423}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-09-09,15861566,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Untold Story of Nat Turner,The Birth of a Nation,6.5,178
3249,0,"[{""id"": 12, ""name"": ""Adventure""}]",http://www.focusfeatures.com/kicks,385736,"[{""id"": 3405, ""name"": ""blow job""}, {""id"": 1173...",en,Kicks,When his hard-earned kicks get snatched by a l...,3.467923,"[{""name"": ""Bystorm Films"", ""id"": 2903}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-09-09,0,80.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They aren't just shoes,Kicks,7.5,18

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
df_movies.loc[:,['id', 'keywords', 'genres', 'title']]

0       [{"id": 1463, "name": "culture clash"}, {"id":...
1       [{"id": 270, "name": "ocean"}, {"id": 726, "na...
2       [{"id": 470, "name": "spy"}, {"id": 818, "name...
3       [{"id": 849, "name": "dc comics"}, {"id": 853,...
4       [{"id": 818, "name": "based on novel"}, {"id":...
5       [{"id": 851, "name": "dual identity"}, {"id": ...
6       [{"id": 1562, "name": "hostage"}, {"id": 2343,...
7       [{"id": 8828, "name": "marvel comic"}, {"id": ...
8       [{"id": 616, "name": "witch"}, {"id": 2343, "n...
9       [{"id": 849, "name": "dc comics"}, {"id": 7002...
10      [{"id": 83, "name": "saving the world"}, {"id"...
11      [{"id": 627, "name": "killing"}, {"id": 1568, ...
12      [{"id": 616, "name": "witch"}, {"id": 663, "na...
13      [{"id": 1556, "name": "texas"}, {"id": 2673, "...
14      [{"id": 83, "name": "saving the world"}, {"id"...
15      [{"id": 818, "name": "based on novel"}, {"id":...
16      [{"id": 242, "name": "new york"}, {"id": 5539,...
17      [{"id": 658, "name": "sea"}, {"id": 1316, "nam...
18      [{"id": 4379, "name": "time travel"}, {"id": 5...
19      [{"id": 417, "name": "corruption"}, {"id": 603...
20      [{"id": 1872, "name": "loss of father"}, {"id"...
21      [{"id": 4147, "name": "robin hood"}, {"id": 43...
22      [{"id": 603, "name": "elves"}, {"id": 604, "na...
23      [{"id": 392, "name": "england"}, {"id": 1461, ...
24      [{"id": 774, "name": "film business"}, {"id": ...
25      [{"id": 2580, "name": "shipwreck"}, {"id": 298...
26      [{"id": 393, "name": "civil war"}, {"id": 6091...
27      [{"id": 1721, "name": "fight"}, {"id": 4410, "...
28      [{"id": 1299, "name": "monster"}, {"id": 1718,...
29      [{"id": 470, "name": "spy"}, {"id": 4289, "nam...
                              ...
4773    [{"id": 1361, "name": "salesclerk"}, {"id": 30...
4774    [{"id": 1566, "name": "dream"}, {"id": 13059, ...
4775               [{"id": 171993, "name": "mumblecore"}]
4776    [{"id": 1438, "name": "office"}, {"id": 9673, ...
4777                                                   []
4778    [{"id": 10022, "name": "rampage"}, {"id": 1454...
4779    [{"id": 305, "name": "moon"}, {"id": 490, "nam...
4780                                                   []
4781    [{"id": 13043, "name": "dating"}, {"id": 15160...
4782    [{"id": 186, "name": "christianity"}, {"id": 4...
4783                 [{"id": 9712, "name": "possession"}]
4784               [{"id": 171993, "name": "mumblecore"}]
4785                                                   []
4786          [{"id": 10183, "name": "independent film"}]
4787                  [{"id": 9715, "name": "superhero"}]
4788    [{"id": 237, "name": "gay"}, {"id": 900, "name...
4789    [{"id": 6782, "name": "addiction"}, {"id": 155...
4790                                                   []
4791             [{"id": 14903, "name": "home invasion"}]
4792    [{"id": 233, "name": "japan"}, {"id": 549, "na...
4793    [{"id": 718, "name": "confession"}, {"id": 100...
4794                                                   []
4795    [{"id": 10726, "name": "gang"}, {"id": 33928, ...
4796    [{"id": 1448, "name": "distrust"}, {"id": 2101...
4797                                                   []
4798    [{"id": 5616, "name": "united states\u2013mexi...
4799                                                   []
4800    [{"id": 248, "name": "date"}, {"id": 699, "nam...
4801                                                   []
4802    [{"id": 1523, "name": "obsession"}, {"id": 224...
Name: keywords, Length: 4803, dtype: object